LOGICSENTENCE
         ::= ( SENTENCE '\n' )+

SENTENCE ::= ( ID ASSIGN ) EXPRESSION | EXPRESSION

EXPRESSION ::= EXPRESSION OR T

T ::= T AND Y | Y


Y ::= Y IMPLICATION F | F

F ::= LEFT_P EXPRESSION RIGHT_P | NOT LEFT_P EXPRESSION RIGHT_P | ID | TRUE | FALSE










